version: '3.8'

services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: course_db
            MYSQL_USER: user
            MYSQL_PASSWORD: studentpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped
    web:
        image: garyclarke/nginx24-multi
        ports:
            - "8080:80"  # Maps port 8080 on the host to port 80 in the container
        volumes:
            - ./public:/var/www/html/public
        depends_on:
            - app  # Ensures Nginx starts after the PHP service
        restart: unless-stopped
    app:
        build:
            context: ./docker
        volumes:
            - .:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql  # Ensures the PHP app service starts after the MySQL service
        restart: unless-stopped

volumes:
    mysql_data:
        driver: local
